language: cpp
sudo: required

notifications:
  email:
    recipients:
      - 3263ta@gmail.com
    on_success: change # default: change
    on_failure: change # default: change

matrix:
  include:
    # Ubuntu14.04
    - os: linux
      dist: trusty

addons:
  apt:
    packages:

before_script:

script:
    - ./setup.sh --help
    - ./setup.sh --no-gpu
